// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABBSq6X_X40POeN8fafx4sXIb_64Z1UVQ',
    appId: '1:332914717990:web:4498779b47613d82d47de7',
    messagingSenderId: '332914717990',
    projectId: 'lachancla-flutter',
    authDomain: 'lachancla-flutter.firebaseapp.com',
    storageBucket: 'lachancla-flutter.appspot.com',
    measurementId: 'G-WTCN4ZTWGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADtq8hpUdLPrwlXxKMXfrDo7SP8h5a1JA',
    appId: '1:332914717990:android:cd4f2fe940a160d8d47de7',
    messagingSenderId: '332914717990',
    projectId: 'lachancla-flutter',
    storageBucket: 'lachancla-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfpT30aKEPjKSTL7c5JpgOvCiSWt0SxtI',
    appId: '1:332914717990:ios:76a989baada8ec79d47de7',
    messagingSenderId: '332914717990',
    projectId: 'lachancla-flutter',
    storageBucket: 'lachancla-flutter.appspot.com',
    iosClientId: '332914717990-3bpgbqd4ljoqlrprh7f873jdpos4dfjm.apps.googleusercontent.com',
    iosBundleId: 'iteso.mx.lachancla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfpT30aKEPjKSTL7c5JpgOvCiSWt0SxtI',
    appId: '1:332914717990:ios:76a989baada8ec79d47de7',
    messagingSenderId: '332914717990',
    projectId: 'lachancla-flutter',
    storageBucket: 'lachancla-flutter.appspot.com',
    iosClientId: '332914717990-3bpgbqd4ljoqlrprh7f873jdpos4dfjm.apps.googleusercontent.com',
    iosBundleId: 'iteso.mx.lachancla',
  );
}
